import app.routers.auth as auth
import app.routers.dashboard as dashboard
import app.routers.properties as properties
import app.routers.units as units
import app.routers.rooms as rooms
import app.routers.tenants as tenants
import app.routers.payments as payments
import app.routers.maintenance as maintenance
import app.routers.announcements as announcements
import app.routers.tenant_portal as tenant_portal
import app.routers.preferences as preferences
